### PR TITLE
[FIX] fixes #125, #129

### LINKED ISSUE #125: [BUG] 'NoneType' object has no attribute 'group'
Version : **0.2.1**

**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows:**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

this relates to this: https://github.com/nishad/udemy-dl/issues/120
except i follow the policy to report this.

i'm running udemy-dl on archlinux.

this course i'm refering to is available for free right now: https://www.udemy.com/javascript-essentials/

the result of this issue is skipped course content:

    udemy-dl -u xxx@xxx.xx -p xxx https://www.udemy.com/javascript-essentials/learn/v4
    [INFO-835] Downloading to: /xxx/udemy/javascript-essentials
    
    [INFO-107] Trying to log in ...
    [INFO-137] Login success.
    [INFO-169] Found course id: 707962
    Getting course data: 5.13% [=-------------------] [CRITICAL-407] Cannot download lecture "Introduction": "'NoneType' object has no attribute 'group'"
    Getting course data: 7.69% [==------------------] [CRITICAL-407] Cannot download lecture "What is Javascript": "'NoneType' object has no attribute 'group'"
    Getting course data: 10.26% [==------------------] [CRITICAL-407] Cannot download lecture "How Javascript works": "'NoneType' object has no attribute 'group'"
    …
    Downloading Video: 005 What is an object
    [CRITICAL-51] aria2c not found. Downloading with builtin downloader
    Downloading: 100.00% [==============================] Done
    …
    [INFO-711] Logging out...
    [INFO-713] Logging out success

### PR DESCRIPTION
**Pull request by mukhlesur-millon**
- [x] I have read and understood the [contributors guide]().
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [x] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

-  fixes #125, #129
- better exception logging
- reduce too many return statement in  extract_lecture_url
- fixes https://github.com/nishad/udemy-dl/issues/125#issuecomment-234702116 for pptx
and some small changes

### CODE REVIEW

**Comment by nishad** [comment]
Kudos @mukhlesur-millon, Thanks for doing this.
:sake: かんぱい !!!

**Comment by madmax2** [comment]
[CRITICAL-418] Cannot download lecture "How to get the most out of the course": "'NoneType' object has no attribute 'group'"

**Comment by madmax2** [comment]
So is this problem fix or not?
I tried to update latest udemy-dl from nishad master and still has same problem.

**Comment by nishad** [comment]
This issue is a duplicate of https://github.com/nishad/udemy-dl/issues/125. Which is adressed in resent development release.

**Comment by vvscode** [comment]
Try
`pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master`

History says that changes already were merged into master

**Pull request merged**
