### PR TITLE
[FEATURE] Add Video quality option for downloading

### PR DESCRIPTION
**Pull request by mukhlesur-millon**
- [x] I have read and understood the [contributors guide]().
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

---

- add Video quality option for downloading.
    * issue: lower video quality #44
    * **limitation:**
       - does nothing when invalid option are given
       - download available highest quality if desire quality is not found (combination is available ex. `360480` or `360480720`)

### CODE REVIEW

**Comment by nishad** [comment]
Thanks @mukhlesur-millon, 

1. About video quality selection, I am thinking of something like, `youtube-dl`s implementation. But  `-F, --list-formats` is far from the real usage scenarios at this stage.

2. What about something like `--video-quality high | low | size` ? 

3. Or even we can use `raw_input()` and `input()` for some options like `--select-video-quality`, when we list out all possible quality variables.

4. I think `video_quality` is much better than `qua` :smile:

**Comment by mukhlesur-millon** [comment]
`--select-video-quality` will be better and it will be easier, add `show common video quality` like `--just-list` and user will select desire quality.

**Comment by nishad** [comment]
`Lower quality` option was in demand, mainly from unethical users. They think that it will help them to get videos faster. :laughing: . That is the main reason for ignoring such requests. 

Everyone likes to have higher quality videos for offline archiving, and we used to have requests like this,  https://github.com/nishad/udemy-dl-windows/issues/54

**Comment by mukhlesur-millon** [comment]
but limited user with limited bandwidth lacking this...

**Comment by nishad** [comment]
I'm not against the idea of a video quality selection. I just ignored it for a while. I was waiting for udemy to fix their vulnerability. Once it is again safe to use, we can add pretty good features. 

You can create a better PR for the same. Until keep this opened. Please concider using meaningful variable names. As I mentioned `video_quality` is much better than `qua`. :sake:

**Comment by nishad** [comment]
`Default` is highest available, as in `youtube-dl`. `Possible Values` can be all values which we use, and if the resolution is not available, it can fall back to next `highest`. :+1:

**Comment by mukhlesur-millon** [comment]
i was asking about aria2c like  `Possible Values: 1-16` `Default: 1`

**Comment by nishad** [comment]
So, if the given value is not available, will it fall back to highest or higher or lowest or lower ?

**Comment by mukhlesur-millon** [comment]
in my PR, if the given value is not available, it will download highest quality

**Comment by nishad** [comment]
1. There should be a validation for the quality parameter. `(1080 | 720 | 480 | 360)`
2. User should get a feedback if it fall back to highest quality.
3. I recommend creating aliases as well like `youtube-dl`. For example `best` for highest, and `worst` for lowest.
4. Better naming for the variable, no more `qua`, but something meaningful.
5. Better help message for quality parameter.

What do you think ?

**Comment by mukhlesur-millon** [comment]
i will try :+1:

**Comment by mukhlesur-millon** [comment]
this is` no longer valid with version of udemy`, so i am closing it.

**Pull request closed without merging**
