### PR TITLE
[FEATURE] add --video-quality and some fixes

### PR DESCRIPTION
**Pull request by mukhlesur-millon**
**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows:**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

- add --video-quality  https://github.com/nishad/udemy-dl/issues/44#issuecomment-211392359

  - `1: 240`, `2: 360`, `3: 480`, `4: 640`, `5: 720`, `6: 1080`

   - can be used as `-q 12346` or `-q 32451` or `-q 2` or `-q 543`
   - for `-q 342` first, it will try to download `480p` then `640p` and finally `360p`. if it is failed to find all quality then it will show an error message and it will skip that lecture.[usually all lecture contain 360p and 720p]

### CODE REVIEW

**Comment by nishad** [comment]
Excellent !!! Accepting, but help message for video quality needs to be a bit more clear to avoid confusion. Like `Quality  1 to 6 where 6 being highest` or even with the resulting quality. Also recommend for an alias like `-q 4` or `-q 640` if both are accepted then awesome !!! 👍 

:sake: かんぱい !!!

**Comment by mukhlesur-millon** [comment]
I have added [downloading lower video quality](https://github.com/nishad/udemy-dl/wiki/Downloading-lower-video-quality) in the wiki.

**Comment by nishad** [comment]
Awesome @mukhlesur-millon. 
Now we have to enable `colorlog` instead of most of the `print` statements, `debug` as a function, and wiki links along with the error messages. Then we'll be ready for next stable release. 

Seems like we can ignore https://github.com/nishad/udemy-dl/issues/101.

**Comment by mukhlesur-millon** [comment]
if #101 happens for default encoding it should fix with @1fce69b4bdf3401d09af77487d0832ebb3d31670

**Comment by mukhlesur-millon** [comment]
@nishad i have added coloredlog but it doesn't works in powershell.

**Comment by tobias-p** [comment]
couldnt find an answer and thought asking here would be best:

which is the default quality if I don't add the "-q" argument?

**Pull request merged**
