### PR TITLE
[IMPROVEMENT] improve download

### PR DESCRIPTION
**Pull request by mukhlesur-millon**
**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows:**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

- improve download #53

### CODE REVIEW

**Comment by nishad** [comment]
What if the user retry with a different downloader after a failed download ? All these downloaders use different methods on resume function. For example `aria2c` cannot resume a broken download from `curl` and vise-versa.

**Comment by mukhlesur-millon** [comment]
i have download lecture_1 51% with curl and rest with aria2 and lecture_2 61% with aria2 and rest with curl. there was not any problem. but there is a problem with aria2, if a lecture is fully downloaded sometimes it shows  `File already exists. Renamed to ...mp4.1`. if `...mp4.1` was completed then `...mp4.2` ..... its not safe to use aria2 as default downloader.

**Comment by mukhlesur-millon** [comment]
i have updated my PR.

**Comment by nishad** [comment]
What about adding a `.part` extension and remove once it is finished ? However, aria2 is capable of utilizing multiple connections. Which makes https://github.com/nishad/udemy-dl/pull/87#issuecomment-205739883 in question. There is a higher change for getting a corrupted file as final output.

**Comment by mukhlesur-millon** [comment]
i have added `.part` and improved downloading. it will not try to download if a lecture already exist. it only rename to original lecture name if it is completed. now it is safe to set `aria2` as default. i have use `builtin`  downloader for m3u8.

**Comment by nishad** [comment]
Seems like some regions, udemy coming up with akmai CDN. We may need to come up with better stream downloaders, something like https://github.com/K-S-V/Scripts/blob/master/AdobeHDS.php.

**Comment by mukhlesur-millon** [comment]
can you please tell me any region name? i need to study with it.

**Pull request merged**
