### PR TITLE
[FEATURE] add --use-ffmpeg and support for captions, quiz and attached file

### LINKED ISSUE #88: [BUG] Cannot download lecture "xxx": "'tuple' object has no attribute 'split'"
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

- No additional requirements.

---

I'm trying to download from a course but there is errors from most of the links.
```Cannot download lecture "Welcome to the course": "'tuple' object has no attribute 'split'"```
I'm already using the trunk sources directly.
```
udemy-dl -s https://www.udemy.com/sketching-for-beginners
Username / Email : 
Password : 
Saving links to: /home/dashie/Vidéos/sketching-for-beginners.txt

Trying to log in ... and we're done.
Searching course id... Found: 382394
Getting course data: 6.98% [=-------------------] Cannot download lecture "Welcome to the course": "'tuple' object has no attribute 'split'"
Getting course data: 9.30% [==------------------] Cannot download lecture "What is Sketching": "'tuple' object has no attribute 'split'"
Getting course data: 11.63% [==------------------] Cannot download lecture "Demonstration - Getting Started": "'tuple' object has no attribute 'split'"
Getting course data: 16.28% [===-----------------] Cannot download lecture "Demonstration - Working With Tone": "'tuple' object has no attribute 'split'"
Getting course data: 23.26% [=====---------------] Cannot download lecture "Demonstration - Learning To See": "'tuple' object has no attribute 'split'"
Getting course data: 27.91% [======--------------] Cannot download lecture "Personal Note": "'tuple' object has no attribute 'split'"
Getting course data: 30.23% [======--------------] Cannot download lecture "What Materials": "'tuple' object has no attribute 'split'"
Getting course data: 34.88% [=======-------------] Cannot download lecture "How Do I Use This Course": "'tuple' object has no attribute 'split'"
Getting course data: 37.21% [=======-------------] Cannot download lecture "How Long Will This Course Take To Complete": "'tuple' object has no attribute 'split'"
Getting course data: 48.84% [==========----------] Cannot download lecture "Basic Mark-Making": "'tuple' object has no attribute 'split'"
Getting course data: 51.16% [==========----------] Cannot download lecture "Simplifying Objects": "'tuple' object has no attribute 'split'"
Getting course data: 53.49% [===========---------] Cannot download lecture "Drawing Styles": "'tuple' object has no attribute 'split'"
Getting course data: 55.81% [===========---------] Cannot download lecture "Capturing Information": "'tuple' object has no attribute 'split'"
Getting course data: 58.14% [============--------] Cannot download lecture "Sketching On The Computer": "'tuple' object has no attribute 'split'"
Getting course data: 60.47% [============--------] Cannot download lecture "Capturing Ideas": "'tuple' object has no attribute 'split'"
Getting course data: 62.79% [=============-------] Cannot download lecture "Recording Notes Using Graphics": "'tuple' object has no attribute 'split'"
Getting course data: 65.12% [=============-------] Cannot download lecture "Adding Banners": "'tuple' object has no attribute 'split'"
Getting course data: 74.42% [===============-----] Cannot download lecture "Drawing in 3 dimensions": "'tuple' object has no attribute 'split'"
Getting course data: 79.07% [================----] Cannot download lecture "Understanding Shading": "'tuple' object has no attribute 'split'"
Getting course data: 86.05% [=================---] Cannot download lecture "Demonstration - Sketching A Feather": "'tuple' object has no attribute 'split'"
Getting course data: 88.37% [==================--] Cannot download lecture "Recreating Proportions": "'tuple' object has no attribute 'split'"
Getting course data: 100.00% [====================] Done
Cannot download lecture "Thank You": "'tuple' object has no attribute 'split'"
Links successfully saved to : /home/dashie/Vidéos/sketching-for-beginners.txt

Logging out... Done
```
The file only have 12 links (some are PDFs).

### PR DESCRIPTION
**Pull request by mukhlesur-millon**
**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows:**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
- add support for `captions`, `quiz`, `attached item` and some changes

- add `ffmpeg` for downloading hls video. but it is not default, user need to add `--use-ffmpeg`. make it default will cause some problem if he do not install it [downloading with m3u8 module and merging them, cause a litle problem. when try to forward video, it looks like a broken video for some seconds.] 

- fix #88

`file structure of courses with captions`

```
├── 01 Introduction
│   ├── 001 Introduction and Installation.mp4
│   ├── 002 What Java Is and How It Works.mp4
│   └── captions
│       ├── 001 Introduction and Installation-EN.srt
│       └── 002 What Java Is and How It Works-EN.srt
```

` file structure of courses with quizzes and attached_files`
```

├── 02 Getting Your Feet Wet With HTML And CSS
│   ├── 009 Editing The Navbar.mp4
│   ├── 010 What The Div.mp4
│   ├── 012 Your First CSS Rule.mp4
│   ├── 013 More CSS Fun.mp4
│   ├── 014 Get Your Font On.mp4
│   ├── 015 Making Fonts Look Goooood.html
│   ├── 016 The Box Model.mp4
│   ├── 017 Bringin In The Images.mp4
│   ├── attached_files
│   │   ├── 009 What The Div
│   │   │   └── First-Site-Lesson-9.zip
│   │   ├── 010 Your First CSS Rule
│   │   │   └── First-Site-Lesson-10.zip
│   │   ├── 011 More CSS Fun
│   │   │   └── First-Site-Lesson-11.zip
│   │   ├── 012 Get Your Font On
│   │   │   └── First-Site-Lesson-12.zip
│   │   ├── 014 The Box Model
│   │   │   └── First-Site-Lesson-14.zip
│   │   └── 015 Bringin In The Images
│   │       ├── Code.png
│   │       ├── First-Site-Lesson-15.zip
│   │       ├── Hero-Image.jpg
│   │       └── Top-Logo.png
│   └── quizzes
│       ├── 002 Quick Review.html
│       └── 003 Quick Review.html
```

i don't know if everything looks ok. if it doesn't, please correct me.

### CODE REVIEW

**Comment by nishad** [comment]
What if we check for `ffmpeg`, and fall back to builtin if `ffmpeg` is not present ? Same as it used to do with curl.

**Comment by nishad** [comment]
:sake: かんぱい !!!

**Comment by mukhlesur-millon** [comment]
if anyone use  `curl` and it is not installed, lecture will be downloaded with `urlopen_dl` or if he add `--use-ffmpeg` and it not installed, he will get m3u8 variant file ends with `.mp4`  it can be played if he is connected with internet [tested only with vlc and default video player]

**Comment by nishad** [comment]
See this for a clear idea on m3u8 https://github.com/k3c/Scripts/blob/master/AdobeHDS.py

**Comment by mukhlesur-millon** [comment]
oh..this already exists! i was trying to understand $$$$. thanks for this.

**Comment by mukhlesur-millon** [comment]
@nishad i have got a better package `livestreamer`. it can handle both `hls` and `hds`. it also support quality selection, for a udemy `hd`  `hls variant` it shows `Available streams: 1200k, 1400k, 180k (worst), 2400k (best), 260k, 800k`  we can easily add it in `requirements.txt` instead of being depended on user.

**Comment by nishad** [comment]
Sure, go ahead. I'll review the PR.

**Comment by Murtadhajfadhil** [comment]
It seems udemy-dl no longer support downloading closed caption ..

**Pull request merged**
