### PR TITLE
[FEATURE] add --external-downloader, add asset type File and some improvement

### PR DESCRIPTION
**Pull request by mukhlesur-millon**
**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows :**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

- add new asset type `File` contain zip, pptx, psd  etc

- add option to select downloader `aria2c as default`

- add draft course download https://github.com/nishad/udemy-dl/issues/62#issuecomment-203041152 @gost

- add requests 2.9.1 #82 

- some correction

### CODE REVIEW

**Comment by nishad** [comment]
@mukhlesur-millon About sub-domains, I got concerns on it's ethical aspect. courses form these sub-domains are owned by the business not the end user. Usually it is employer who purchase this course and gives access to employees though the orporate account.

**Comment by mukhlesur-millon** [comment]
got it... i have updated my PR.

**Comment by nishad** [comment]
:sake: かんぱい !!!

**Comment by mukhlesur-millon** [comment]
ধন্যবাদ :smile:

**Pull request merged**
