### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by mukhlesur-millon**
- add supported asset type in a list
- support new asset Type Presentation
- improve url parsing 
- add new asset type article
- fix failed to get csrf toekn
- add new argument --external-downloader, -d
- support external downloader idm for windows. …

### CODE REVIEW

**Comment by nishad** [comment]
I'm not in favor of supporting idm, as it is a proprietary program, and it is much windows specific.

**Comment by mukhlesur-millon** [comment]
i will add other fast cross platform downloader, quiz, attached files later.

on windows there there is no other option without adding idm... linux user can use curl, aria2 etc.
i will get up to 350 KBps if i use curl, aria2 on windows and i can get  upto 2.5 MBps using idm as i have tested.

**Comment by nishad** [comment]
`udemy-dl` is following the philosophy of such tools like `youtube-dl`. Only console basd external downloaders are in proposal. IDM being a closed source solution and I don't want to extend or support something like that, which is proprietary. 

Udemy courses are lifelong purchases, so speed is not a big thing. The possible external downloads are `aria2c,axel,curl,httpie and wget`.

**Comment by mukhlesur-millon** [comment]
ok

**Pull request closed without merging**
