### PR TITLE
[FIX] Fix #92 Password prompt Python 2.7 Windows

### LINKED ISSUE #92: [BUG] Python 2.7 + Windows = password prompting fails
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

So, when using the library on windows with python 2.7 (2.7.10 in my case), password prompt fails with the following message:

```
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Rony\Desktop\udemy-dl-master\src\udemy_dl\__main__.py", line 8, in <module>
    main()
  File "udemy_dl\udemy_dl.py", line 680, in main
    password = getpass.getpass(prompt='Password : ')
  File "C:\Python27\lib\getpass.py", line 95, in win_getpass
    msvcrt.putch(c)
TypeError: must be char, not unicode
```

Happens not only here: [example#1](https://reviews.reviewboard.org/r/6983/diff/4#index_header), [example#2](https://bitbucket.org/ZyX_I/gibiexport/issues/2/error-getting-password-on-windows)

I will fix it and create a pull request soon hopefully.

### PR DESCRIPTION
**Pull request by ronlut**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

### CODE REVIEW

**Comment by nishad** [comment]
What will happen, if we make `encode('utf8')` default for all platforms and Python versions instead of creating a separate function?

**Comment by ronlut** [comment]
I think it'll be ok.. Encoding an encoded string should have no effect. Want me to change it?

**Comment by nishad** [comment]
If possible, you can run a couple of test with different python versions and platforms to ensure that. You can modify this pull request according to the results. In that way it will be much platform neutral :)

**Comment by williseverything** [comment]
Hello , could you please tell me whats the solution to the error "string indices must be integers"  ?

**Comment by nishad** [comment]
@williseverything right now `-p` can deal  this issue.

**Comment by ronlut** [comment]
@nishad Just to add on before changing.. I isolated the problem to this import: `from __future__ import unicode_literals`.
This import causes the prompt to be unicode and then getpass throws an exception..

I have a cleaner solution but don't know how you feel about it:
I can leave the file almost untouched by just changing this:
```
if not username:
    username = input("Username / Email : ")
if not password:
    password = getpass.getpass(prompt='Password : ')
```

to this:
```
if not username:
    username = input("Username / Email: ")
if not password:
    password = getpass.getpass()
```

Default prompt is 'Password: ' anyway so it'll solve the problem. I even changed the input string to have no space before the colon for the convention.

**Comment by mukhlesur-millon** [comment]
@ronlut i was thinking it like this
```
if not password:
    if sys.version_info[0] is 2:
    	password = getpass.getpass('Password: '.encode('utf-8'))
    else:
    	password = getpass.getpass()
```
as `getpass` on python 2 also use `AskPassword` from `EasyDialogs`.

**Comment by nishad** [comment]
Hopefully it is fixed in v0.2.1

**Pull request closed without merging**
